# Generated by Django 5.2 on 2025-04-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_userprofile_timezone_alter_claim_claim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='amount_claimed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='fraud_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='incident_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_fraudulent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='medical_record',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
    ]
