# Generated by Django 5.2 on 2025-04-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_amount_claimed_claim_fraud_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='hospital_clinic_provider_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
