# Generated by Django 5.2 on 2025-04-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_claim_admission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='amount_claimed',
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('IPD', 'IPD'), ('OPD', 'OPD'), ('Dental', 'Dental'), ('Eye', 'Eye'), ('Maternity', 'Maternity')], default='IPD', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='consultation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='coverage',
            field=models.CharField(choices=[('Full', 'Full Coverage'), ('Partial', 'Partial Coverage'), ('None', 'No Coverage')], default='Full', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='hospital',
            field=models.CharField(choices=[('Apollo', 'Apollo Hospital'), ('Fortis', 'Fortis Hospital'), ('AIIMS', 'AIIMS'), ('CMC', 'Christian Medical College'), ('Other', 'Other')], default='Apollo', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='medication',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='others',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='total_claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
