# Generated by Django 5.2 on 2025-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_remove_claim_amount_claimed_claim_claim_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='hospital',
        ),
        migrations.AlterField(
            model_name='claim',
            name='hospital_clinic_provider_name',
            field=models.CharField(choices=[('Apollo', 'Apollo Hospital'), ('Fortis', 'Fortis Hospital'), ('AIIMS', 'AIIMS'), ('CMC', 'Christian Medical College'), ('Other', 'Other')], default='Apollo', max_length=255),
        ),
    ]
