# Generated by Django 5.2 on 2025-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_remove_claim_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='coverage',
            field=models.CharField(blank=True, choices=[('Full', 'Full Coverage'), ('Partial', 'Partial Coverage'), ('None', 'No Coverage')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='hospital_clinic_provider_name',
            field=models.CharField(blank=True, choices=[('Apollo', 'Apollo Hospital'), ('Fortis', 'Fortis Hospital'), ('AIIMS', 'AIIMS'), ('CMC', 'Christian Medical College'), ('Other', 'Other')], default=None, max_length=255, null=True),
        ),
    ]
