# Generated by Django 5.2 on 2025-04-13 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_alter_claim_coverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='medical_record',
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_records/')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='claims.claim')),
            ],
        ),
    ]
