# Generated by Django 5.2 on 2025-04-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_remove_claim_medical_record_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='medical_record',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
