# Generated by Django 5.2 on 2025-04-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_claimdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimDocument',
        ),
    ]
