# Generated by Django 5.2 on 2025-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_claimdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
