# Generated by Django 5.2 on 2025-04-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_alter_claim_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='medical_record',
        ),
    ]
