# Generated by Django 5.2 on 2025-04-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0016_alter_claim_hospital_clinic_provider_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimcontractdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
