# Generated by Django 5.2 on 2025-04-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0017_claimcontractdocument_document_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimcontractdocument',
            old_name='documents',
            new_name='contract_documents',
        ),
    ]
