# Generated by Django 5.2 on 2025-04-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0018_rename_documents_claimcontractdocument_contract_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
