# Generated by Django 5.2 on 2025-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0019_userprofile_imid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
